name: git_hub_users
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0




  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  http: ^1.2.1
  google_fonts: ^6.2.1

flutter_native_splash:

  android: true
  ios: true
  web: false

  # color: "0x000000"
  # background_image: assets/images/black.jpg
  image: assets/images/git_hub.jpg


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  generate: true


  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #


